// Flutter supports ARM32, ARM64 and x86_64. The JNI plugin also enables
// obsolete x86 by default, which current Android NDKs no longer support.
allprojects { project ->
    if (project.name == 'jni') {
        project.plugins.withId('com.android.library') {
            project.android.defaultConfig.ndk.abiFilters.clear()
            project.android.defaultConfig.ndk.abiFilters.addAll(['armeabi-v7a', 'arm64-v8a', 'x86_64'])
        }
    }
}
